"""Initial schema

Revision ID: 391038f521ce
Revises: None
Create Date: 2026-08-02 16:00:31.675935

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '391038f521ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_is_deleted'), 'organizations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('sdk_versions',
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('min_compatible_backend', sa.String(length=50), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdk_versions_created_at'), 'sdk_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sdk_versions_is_deleted'), 'sdk_versions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_sdk_versions_language'), 'sdk_versions', ['language'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_project_org_slug', 'projects', ['organization_id', 'slug'], unique=True)
    op.create_index(op.f('ix_projects_created_at'), 'projects', ['created_at'], unique=False)
    op.create_index(op.f('ix_projects_is_deleted'), 'projects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('teams',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_created_at'), 'teams', ['created_at'], unique=False)
    op.create_index(op.f('ix_teams_is_deleted'), 'teams', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teams_organization_id'), 'teams', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_is_deleted'), 'api_keys', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_is_deleted'), 'audit_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_project_id'), 'audit_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('environments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_created_at'), 'environments', ['created_at'], unique=False)
    op.create_index(op.f('ix_environments_is_deleted'), 'environments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('vector_collection', sa.String(length=100), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_knowledge_project_hash', 'knowledge_documents', ['project_id', 'file_hash'], unique=True)
    op.create_index(op.f('ix_knowledge_documents_created_at'), 'knowledge_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_file_hash'), 'knowledge_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_is_deleted'), 'knowledge_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_is_indexed'), 'knowledge_documents', ['is_indexed'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_project_id'), 'knowledge_documents', ['project_id'], unique=False)
    op.create_table('notification_configs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('target_url', sa.String(length=500), nullable=True),
    sa.Column('settings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_configs_created_at'), 'notification_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_configs_is_deleted'), 'notification_configs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notification_configs_project_id'), 'notification_configs', ['project_id'], unique=False)
    op.create_table('organization_members',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_created_at'), 'organization_members', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_members_is_deleted'), 'organization_members', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_user_id'), 'organization_members', ['user_id'], unique=False)
    op.create_table('rate_limit_rules',
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('max_requests', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_rules_created_at'), 'rate_limit_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_rules_is_deleted'), 'rate_limit_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rate_limit_rules_project_id'), 'rate_limit_rules', ['project_id'], unique=False)
    op.create_table('services',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('framework', sa.String(length=50), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_project_name', 'services', ['project_id', 'name'], unique=True)
    op.create_index(op.f('ix_services_created_at'), 'services', ['created_at'], unique=False)
    op.create_index(op.f('ix_services_is_deleted'), 'services', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_services_project_id'), 'services', ['project_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_deleted'), 'user_sessions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_sessions_token_hash'), 'user_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('deployments',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('commit_hash', sa.String(length=100), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('deployed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_commit_hash'), 'deployments', ['commit_hash'], unique=False)
    op.create_index(op.f('ix_deployments_created_at'), 'deployments', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployments_is_deleted'), 'deployments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_index(op.f('ix_deployments_service_id'), 'deployments', ['service_id'], unique=False)
    op.create_index(op.f('ix_deployments_version'), 'deployments', ['version'], unique=False)
    op.create_table('incidents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('root_cause_summary', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incidents_project_status', 'incidents', ['project_id', 'status'], unique=False)
    op.create_index('idx_incidents_severity', 'incidents', ['project_id', 'severity'], unique=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.create_index(op.f('ix_incidents_is_deleted'), 'incidents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_incidents_project_id'), 'incidents', ['project_id'], unique=False)
    op.create_index(op.f('ix_incidents_service_id'), 'incidents', ['service_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_started_at'), 'incidents', ['started_at'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('telemetry_exceptions',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exception_type', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stacktrace', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('function_name', sa.String(length=255), nullable=True),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exceptions_project_type_ts', 'telemetry_exceptions', ['project_id', 'exception_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_created_at'), 'telemetry_exceptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_exception_type'), 'telemetry_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_is_deleted'), 'telemetry_exceptions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_project_id'), 'telemetry_exceptions', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_service_id'), 'telemetry_exceptions', ['service_id'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_timestamp'), 'telemetry_exceptions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_exceptions_trace_id'), 'telemetry_exceptions', ['trace_id'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('logger_name', sa.String(length=255), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_project_ts', 'telemetry_logs', ['project_id', 'timestamp'], unique=False)
    op.create_index('idx_logs_service_level_ts', 'telemetry_logs', ['service_id', 'level', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_created_at'), 'telemetry_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_is_deleted'), 'telemetry_logs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_level'), 'telemetry_logs', ['level'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_project_id'), 'telemetry_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_service_id'), 'telemetry_logs', ['service_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_span_id'), 'telemetry_logs', ['span_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_timestamp'), 'telemetry_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_trace_id'), 'telemetry_logs', ['trace_id'], unique=False)
    op.create_table('telemetry_metrics',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_project_name_ts', 'telemetry_metrics', ['project_id', 'name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_created_at'), 'telemetry_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_is_deleted'), 'telemetry_metrics', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_name'), 'telemetry_metrics', ['name'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_project_id'), 'telemetry_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_service_id'), 'telemetry_metrics', ['service_id'], unique=False)
    op.create_index(op.f('ix_telemetry_metrics_timestamp'), 'telemetry_metrics', ['timestamp'], unique=False)
    op.create_table('telemetry_traces',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('operation_name', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_traces_duration', 'telemetry_traces', ['project_id', 'duration_ms'], unique=False)
    op.create_index('idx_traces_project_trace_id', 'telemetry_traces', ['project_id', 'trace_id'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_created_at'), 'telemetry_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_is_deleted'), 'telemetry_traces', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_operation_name'), 'telemetry_traces', ['operation_name'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_project_id'), 'telemetry_traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_service_id'), 'telemetry_traces', ['service_id'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_span_id'), 'telemetry_traces', ['span_id'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_timestamp'), 'telemetry_traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_traces_trace_id'), 'telemetry_traces', ['trace_id'], unique=False)
    op.create_table('incident_timelines',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timelines_created_at'), 'incident_timelines', ['created_at'], unique=False)
    op.create_index(op.f('ix_incident_timelines_incident_id'), 'incident_timelines', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incident_timelines_is_deleted'), 'incident_timelines', ['is_deleted'], unique=False)
    op.create_table('notification_histories',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('channel_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_histories_created_at'), 'notification_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_histories_incident_id'), 'notification_histories', ['incident_id'], unique=False)
    op.create_index(op.f('ix_notification_histories_is_deleted'), 'notification_histories', ['is_deleted'], unique=False)
    op.create_table('rca_reports',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=False),
    sa.Column('timeline_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('historical_matches_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fix_recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prevention_actions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=20), nullable=False),
    sa.Column('reasoning_tree_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rca_reports_created_at'), 'rca_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_rca_reports_incident_id'), 'rca_reports', ['incident_id'], unique=True)
    op.create_index(op.f('ix_rca_reports_is_deleted'), 'rca_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_rca_reports_project_id'), 'rca_reports', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rca_reports_project_id'), table_name='rca_reports')
    op.drop_index(op.f('ix_rca_reports_is_deleted'), table_name='rca_reports')
    op.drop_index(op.f('ix_rca_reports_incident_id'), table_name='rca_reports')
    op.drop_index(op.f('ix_rca_reports_created_at'), table_name='rca_reports')
    op.drop_table('rca_reports')
    op.drop_index(op.f('ix_notification_histories_is_deleted'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_incident_id'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_created_at'), table_name='notification_histories')
    op.drop_table('notification_histories')
    op.drop_index(op.f('ix_incident_timelines_is_deleted'), table_name='incident_timelines')
    op.drop_index(op.f('ix_incident_timelines_incident_id'), table_name='incident_timelines')
    op.drop_index(op.f('ix_incident_timelines_created_at'), table_name='incident_timelines')
    op.drop_table('incident_timelines')
    op.drop_index(op.f('ix_telemetry_traces_trace_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_timestamp'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_span_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_service_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_project_id'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_operation_name'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_is_deleted'), table_name='telemetry_traces')
    op.drop_index(op.f('ix_telemetry_traces_created_at'), table_name='telemetry_traces')
    op.drop_index('idx_traces_project_trace_id', table_name='telemetry_traces')
    op.drop_index('idx_traces_duration', table_name='telemetry_traces')
    op.drop_table('telemetry_traces')
    op.drop_index(op.f('ix_telemetry_metrics_timestamp'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_service_id'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_project_id'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_name'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_is_deleted'), table_name='telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_metrics_created_at'), table_name='telemetry_metrics')
    op.drop_index('idx_metrics_project_name_ts', table_name='telemetry_metrics')
    op.drop_table('telemetry_metrics')
    op.drop_index(op.f('ix_telemetry_logs_trace_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_timestamp'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_span_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_service_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_project_id'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_level'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_is_deleted'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_created_at'), table_name='telemetry_logs')
    op.drop_index('idx_logs_service_level_ts', table_name='telemetry_logs')
    op.drop_index('idx_logs_project_ts', table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_telemetry_exceptions_trace_id'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_timestamp'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_service_id'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_project_id'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_is_deleted'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_exception_type'), table_name='telemetry_exceptions')
    op.drop_index(op.f('ix_telemetry_exceptions_created_at'), table_name='telemetry_exceptions')
    op.drop_index('idx_exceptions_project_type_ts', table_name='telemetry_exceptions')
    op.drop_table('telemetry_exceptions')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_started_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_project_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_is_deleted'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.drop_index('idx_incidents_severity', table_name='incidents')
    op.drop_index('idx_incidents_project_status', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_deployments_version'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_service_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_is_deleted'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_created_at'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_commit_hash'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_deleted'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_services_project_id'), table_name='services')
    op.drop_index(op.f('ix_services_is_deleted'), table_name='services')
    op.drop_index(op.f('ix_services_created_at'), table_name='services')
    op.drop_index('idx_service_project_name', table_name='services')
    op.drop_table('services')
    op.drop_index(op.f('ix_rate_limit_rules_project_id'), table_name='rate_limit_rules')
    op.drop_index(op.f('ix_rate_limit_rules_is_deleted'), table_name='rate_limit_rules')
    op.drop_index(op.f('ix_rate_limit_rules_created_at'), table_name='rate_limit_rules')
    op.drop_table('rate_limit_rules')
    op.drop_index(op.f('ix_organization_members_user_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_is_deleted'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_created_at'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_notification_configs_project_id'), table_name='notification_configs')
    op.drop_index(op.f('ix_notification_configs_is_deleted'), table_name='notification_configs')
    op.drop_index(op.f('ix_notification_configs_created_at'), table_name='notification_configs')
    op.drop_table('notification_configs')
    op.drop_index(op.f('ix_knowledge_documents_project_id'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_is_indexed'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_is_deleted'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_file_hash'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_created_at'), table_name='knowledge_documents')
    op.drop_index('idx_knowledge_project_hash', table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_is_deleted'), table_name='environments')
    op.drop_index(op.f('ix_environments_created_at'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_project_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_is_deleted'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_is_deleted'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_organization_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_is_deleted'), table_name='teams')
    op.drop_index(op.f('ix_teams_created_at'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_deleted'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_at'), table_name='projects')
    op.drop_index('idx_project_org_slug', table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_sdk_versions_language'), table_name='sdk_versions')
    op.drop_index(op.f('ix_sdk_versions_is_deleted'), table_name='sdk_versions')
    op.drop_index(op.f('ix_sdk_versions_created_at'), table_name='sdk_versions')
    op.drop_table('sdk_versions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_deleted'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
